name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd Ai-Devops-Project || git clone https://github.com/yash-deshpande24/Ai-Devops-Project.git
            cd Ai-Devops-Project
            git pull origin main
            npm install
            pm2 restart app || pm2 start app.js --name app
